include: package:lints/recommended.yaml

analyzer:
  exclude:
    - example/flutter_cypher_lab/**
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    dead_code: error
    unused_import: error
    unused_local_variable: error

linter:
  rules:
    - avoid_dynamic_calls
    - directives_ordering
    - prefer_final_locals
    - unawaited_futures
